/* ==========================================================================
   products.js
   --------------------------------------------------------------------------
   THE single source of truth for every product on the VVX Noir site.
   No product should ever be hardcoded into an HTML file again — every
   product card anywhere on the site (homepage sections, collection grid,
   future product page, future search) is generated FROM this file.

   Field reference (every product should aim to fill all of these):
     id            - number, unique
     slug          - string, unique, URL-safe (used for product.html?slug=)
     name          - display name
     description   - short marketing description
     price         - base price (number)
     discountPrice - sale price if on sale, otherwise null
     currency      - e.g. "ETB"
     gender        - "men" | "women" | "unisex"
     category      - top-level category, e.g. "jackets", "shoes", "belts",
                      "tops", "pants", "handbags", "outfits"
     subcategory   - finer grouping, e.g. "leather-jackets", "clutches"
     style         - aesthetic tag, e.g. "goth", "y2k", "military", "vintage"
     collection    - named collection, e.g. "vintage", "full-outfits", "gamers"
     color         - primary color
     material      - primary material
     sizes         - array of available sizes
     stock         - integer units in stock
     featured      - boolean, show in "Featured" sections
     newArrival    - boolean
     bestSeller    - boolean, show in "Most Selling and Trending"
     sale          - boolean, currently discounted
     rating        - number 0-5
     reviews       - integer review count
     tags          - array of free-text search tags
     thumbnail     - default product image (used in grids/cards)
     heroImage     - larger image (used on hover / product page hero)
     galleryImages - array of additional images for the product page
     dateAdded     - ISO date string, used for "newArrival"/sorting
   ========================================================================== */

const PRODUCTS = [
    {
        id: 1,
        slug: "goth-f1-leather-jacket",
        name: "Goth F1 Leather Jacket (U.S.A.F)",
        description: "Dark aviator-inspired leather jacket with military detailing.",
        price: 2500,
        discountPrice: null,
        currency: "ETB",
        gender: "men",
        category: "jackets",
        subcategory: "leather-jackets",
        style: "goth",
        collection: null,
        color: "black",
        material: "leather",
        sizes: ["S", "M", "L", "XL"],
        stock: 14,
        featured: true,
        newArrival: false,
        bestSeller: true,
        sale: false,
        rating: 4,
        reviews: 38,
        tags: ["jacket", "leather", "goth", "military", "usaf", "men"],
        thumbnail: "./Images/front jacket.PNG",
        heroImage: "./Images/Back ward Jacket.PNG",
        galleryImages: ["./Images/front jacket.PNG", "./Images/Back ward Jacket.PNG"],
        dateAdded: "2026-02-10"
    },
    {
        id: 2,
        slug: "y2k-platform-sneakers",
        name: "Y2K Platform Sneakers",
        description: "Chunky 2000s-inspired sneakers built for the alt aesthetic.",
        price: 1450,
        discountPrice: null,
        currency: "ETB",
        gender: "men",
        category: "shoes",
        subcategory: "sneakers",
        style: "y2k",
        collection: "vintage",
        color: "white",
        material: "synthetic",
        sizes: ["40", "41", "42", "43", "44"],
        stock: 22,
        featured: false,
        newArrival: true,
        bestSeller: false,
        sale: false,
        rating: 4.2,
        reviews: 11,
        tags: ["shoes", "sneakers", "y2k", "men", "vintage"],
        thumbnail: "./Images/VVX/y2k alt.png",
        heroImage: "./Images/VVX/y2k alt.png",
        galleryImages: ["./Images/VVX/y2k alt.png"],
        dateAdded: "2026-05-02"
    },
    {
        id: 3,
        slug: "military-combat-boots",
        name: "Military Combat Boots",
        description: "Rugged combat boots with reinforced stitching and steel eyelets.",
        price: 1980,
        discountPrice: 1680,
        currency: "ETB",
        gender: "men",
        category: "shoes",
        subcategory: "boots",
        style: "military",
        collection: null,
        color: "black",
        material: "leather",
        sizes: ["40", "41", "42", "43", "44", "45"],
        stock: 9,
        featured: true,
        newArrival: false,
        bestSeller: true,
        sale: true,
        rating: 4.6,
        reviews: 54,
        tags: ["shoes", "boots", "military", "men"],
        thumbnail: "./Images/VVX/Military Landing.jfif",
        heroImage: "./Images/VVX/Military Landing.jfif",
        galleryImages: ["./Images/VVX/Military Landing.jfif"],
        dateAdded: "2026-01-20"
    },
    {
        id: 4,
        slug: "goth-buckle-shoes",
        name: "Goth Buckle Shoes",
        description: "Dark platform shoes with triple-buckle straps.",
        price: 1620,
        discountPrice: null,
        currency: "ETB",
        gender: "unisex",
        category: "shoes",
        subcategory: "platforms",
        style: "goth",
        collection: null,
        color: "black",
        material: "faux leather",
        sizes: ["38", "39", "40", "41", "42"],
        stock: 17,
        featured: false,
        newArrival: true,
        bestSeller: false,
        sale: false,
        rating: 4.3,
        reviews: 9,
        tags: ["shoes", "goth", "platforms", "unisex"],
        thumbnail: "./Images/VVX/Goth.jpg",
        heroImage: "./Images/VVX/Goth.jpg",
        galleryImages: ["./Images/VVX/Goth.jpg"],
        dateAdded: "2026-04-18"
    },
    {
        id: 5,
        slug: "military-leather-belt",
        name: "Military Leather Belt",
        description: "Heavy-duty leather belt with a matte steel military buckle.",
        price: 620,
        discountPrice: null,
        currency: "ETB",
        gender: "men",
        category: "belts",
        subcategory: "military-belts",
        style: "military",
        collection: null,
        color: "brown",
        material: "leather",
        sizes: ["S", "M", "L"],
        stock: 40,
        featured: false,
        newArrival: false,
        bestSeller: false,
        sale: false,
        rating: 4.1,
        reviews: 6,
        tags: ["belt", "military", "men", "leather"],
        thumbnail: "./Images/Belt Nav men.jpg",
        heroImage: "./Images/Belt Nav men.jpg",
        galleryImages: ["./Images/Belt Nav men.jpg", "./Images/Belt nav 3.jpg"],
        dateAdded: "2026-03-01"
    },
    {
        id: 6,
        slug: "classic-studded-belt",
        name: "Classic Studded Belt",
        description: "Everyday leather belt finished with subtle stud detailing.",
        price: 540,
        discountPrice: 460,
        currency: "ETB",
        gender: "men",
        category: "belts",
        subcategory: "other-belts",
        style: "goth",
        collection: null,
        color: "black",
        material: "leather",
        sizes: ["S", "M", "L", "XL"],
        stock: 31,
        featured: false,
        newArrival: false,
        bestSeller: false,
        sale: true,
        rating: 3.9,
        reviews: 4,
        tags: ["belt", "studded", "men"],
        thumbnail: "./Images/Belt nav 4.jpg",
        heroImage: "./Images/Belt nav 4.jpg",
        galleryImages: ["./Images/Belt nav 4.jpg"],
        dateAdded: "2026-02-27"
    },
    {
        id: 7,
        slug: "mens-winter-coat",
        name: "Men's Heavyweight Winter Coat",
        description: "Insulated wool-blend coat built for the coldest months.",
        price: 3200,
        discountPrice: null,
        currency: "ETB",
        gender: "men",
        category: "jackets",
        subcategory: "winter-coats",
        style: "goth",
        collection: null,
        color: "charcoal",
        material: "wool blend",
        sizes: ["M", "L", "XL", "XXL"],
        stock: 8,
        featured: false,
        newArrival: false,
        bestSeller: false,
        sale: false,
        rating: 4.4,
        reviews: 15,
        tags: ["jacket", "coat", "winter", "men"],
        thumbnail: "./Images/Belt Nav man 2.jpg",
        heroImage: "./Images/Belt Nav man 2.jpg",
        galleryImages: ["./Images/Belt Nav man 2.jpg"],
        dateAdded: "2025-11-05"
    },
    {
        id: 8,
        slug: "womens-leather-tote",
        name: "Women's Leather Tote",
        description: "Structured everyday tote in full-grain leather.",
        price: 1890,
        discountPrice: null,
        currency: "ETB",
        gender: "women",
        category: "handbags",
        subcategory: "totes",
        style: null,
        collection: null,
        color: "tan",
        material: "leather",
        sizes: [],
        stock: 12,
        featured: true,
        newArrival: false,
        bestSeller: true,
        sale: false,
        rating: 4.7,
        reviews: 29,
        tags: ["handbag", "tote", "women", "leather"],
        thumbnail: "./Images/WOMEN 2.PNG",
        heroImage: "./Images/WOMEN 2.PNG",
        galleryImages: ["./Images/WOMEN 2.PNG"],
        dateAdded: "2026-01-30"
    },
    {
        id: 9,
        slug: "womens-mini-clutch",
        name: "Women's Mini Clutch",
        description: "Compact evening clutch with a magnetic clasp.",
        price: 980,
        discountPrice: 830,
        currency: "ETB",
        gender: "women",
        category: "handbags",
        subcategory: "clutches",
        style: "y2k",
        collection: null,
        color: "black",
        material: "leather",
        sizes: [],
        stock: 19,
        featured: false,
        newArrival: true,
        bestSeller: false,
        sale: true,
        rating: 4.0,
        reviews: 7,
        tags: ["handbag", "clutch", "women", "y2k"],
        thumbnail: "./Images/WOMEN NAV.png",
        heroImage: "./Images/WOMEN NAV.png",
        galleryImages: ["./Images/WOMEN NAV.png"],
        dateAdded: "2026-05-15"
    },
    {
        id: 10,
        slug: "womens-half-jacket",
        name: "Women's Half Leather Jacket",
        description: "Cropped leather jacket with a fitted silhouette.",
        price: 2150,
        discountPrice: null,
        currency: "ETB",
        gender: "women",
        category: "jackets",
        subcategory: "half-jackets",
        style: "goth",
        collection: null,
        color: "black",
        material: "leather",
        sizes: ["XS", "S", "M", "L"],
        stock: 11,
        featured: false,
        newArrival: false,
        bestSeller: false,
        sale: false,
        rating: 4.5,
        reviews: 18,
        tags: ["jacket", "women", "goth", "leather"],
        thumbnail: "./Images/WOMEN 2.PNG",
        heroImage: "./Images/WOMEN 2.PNG",
        galleryImages: ["./Images/WOMEN 2.PNG"],
        dateAdded: "2026-03-22"
    },
    {
        id: 11,
        slug: "womens-full-jacket",
        name: "Women's Full-Length Leather Jacket",
        description: "Floor-grazing statement jacket in matte black leather.",
        price: 2890,
        discountPrice: null,
        currency: "ETB",
        gender: "women",
        category: "jackets",
        subcategory: "full-jackets",
        style: "goth",
        collection: null,
        color: "black",
        material: "leather",
        sizes: ["S", "M", "L"],
        stock: 6,
        featured: true,
        newArrival: true,
        bestSeller: false,
        sale: false,
        rating: 4.8,
        reviews: 21,
        tags: ["jacket", "women", "goth", "leather"],
        thumbnail: "./Images/WOMEN NAV.png",
        heroImage: "./Images/WOMEN NAV.png",
        galleryImages: ["./Images/WOMEN NAV.png"],
        dateAdded: "2026-06-01"
    },
    {
        id: 12,
        slug: "his-and-hers-combo-outfit",
        name: "Him & Her Combo Outfit",
        description: "Matching two-piece outfit set for couples.",
        price: 4200,
        discountPrice: 3600,
        currency: "ETB",
        gender: "unisex",
        category: "outfits",
        subcategory: "combos",
        style: null,
        collection: "full-outfits",
        color: "black",
        material: "mixed",
        sizes: ["S", "M", "L", "XL"],
        stock: 5,
        featured: true,
        newArrival: false,
        bestSeller: false,
        sale: true,
        rating: 4.5,
        reviews: 12,
        tags: ["outfit", "combo", "couples", "full-outfits"],
        thumbnail: "./Images/collar dogs.PNG",
        heroImage: "./Images/Leash dogs.PNG",
        galleryImages: ["./Images/collar dogs.PNG", "./Images/Leash dogs.PNG"],
        dateAdded: "2026-04-02"
    },
    {
        id: 13,
        slug: "anime-graphic-tee",
        name: "Anime Graphic Tee",
        description: "Oversized cotton tee with an original anime-inspired print.",
        price: 780,
        discountPrice: null,
        currency: "ETB",
        gender: "unisex",
        category: "tops",
        subcategory: "t-shirts",
        style: null,
        collection: "gamers",
        color: "black",
        material: "cotton",
        sizes: ["S", "M", "L", "XL"],
        stock: 25,
        featured: false,
        newArrival: true,
        bestSeller: false,
        sale: false,
        rating: 4.2,
        reviews: 8,
        tags: ["top", "tee", "gamers", "anime", "unisex"],
        thumbnail: "./Images/QODA.png",
        heroImage: "./Images/QODA.png",
        galleryImages: ["./Images/QODA.png"],
        dateAdded: "2026-05-28"
    },
    {
        id: 14,
        slug: "vintage-cargo-pants",
        name: "Vintage Cargo Pants",
        description: "Faded utility cargo pants sourced in the vintage collection.",
        price: 1120,
        discountPrice: null,
        currency: "ETB",
        gender: "unisex",
        category: "pants",
        subcategory: "cargo",
        style: "vintage",
        collection: "vintage",
        color: "olive",
        material: "cotton twill",
        sizes: ["28", "30", "32", "34", "36"],
        stock: 16,
        featured: false,
        newArrival: false,
        bestSeller: false,
        sale: false,
        rating: 4.1,
        reviews: 5,
        tags: ["pants", "cargo", "vintage", "unisex"],
        thumbnail: "./Images/wkipa.png",
        heroImage: "./Images/wkipa.png",
        galleryImages: ["./Images/wkipa.png"],
        dateAdded: "2025-12-14"
    },
    {
        id: 15,
        slug: "goth-mesh-top",
        name: "Goth Mesh Layered Top",
        description: "Sheer mesh top designed to be layered over basics.",
        price: 690,
        discountPrice: 590,
        currency: "ETB",
        gender: "women",
        category: "tops",
        subcategory: "mesh",
        style: "goth",
        collection: null,
        color: "black",
        material: "mesh",
        sizes: ["XS", "S", "M", "L"],
        stock: 20,
        featured: false,
        newArrival: true,
        bestSeller: false,
        sale: true,
        rating: 4.3,
        reviews: 10,
        tags: ["top", "goth", "women", "mesh"],
        thumbnail: "./Images/LEER.png",
        heroImage: "./Images/LEER.png",
        galleryImages: ["./Images/LEER.png"],
        dateAdded: "2026-05-08"
    },
    {
        id: 16,
        slug: "y2k-low-rise-jeans",
        name: "Y2K Low-Rise Jeans",
        description: "Faded low-rise denim straight from the 2000s archive.",
        price: 1340,
        discountPrice: null,
        currency: "ETB",
        gender: "women",
        category: "pants",
        subcategory: "jeans",
        style: "y2k",
        collection: "vintage",
        color: "blue",
        material: "denim",
        sizes: ["25", "26", "27", "28", "29"],
        stock: 13,
        featured: false,
        newArrival: false,
        bestSeller: true,
        sale: false,
        rating: 4.6,
        reviews: 24,
        tags: ["pants", "jeans", "y2k", "women", "vintage"],
        thumbnail: "./Images/Pelle.png",
        heroImage: "./Images/Pelle.png",
        galleryImages: ["./Images/Pelle.png"],
        dateAdded: "2026-02-19"
    }
];

/* Expose globally — loaded as a plain script before all other modules
   so PRODUCTS is available on window without a bundler/build step. */
if (typeof window !== "undefined") {
    window.PRODUCTS = PRODUCTS;
}
